#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

selected=$(find $SCRIPT_DIR -maxdepth 1 -type f | fzf)

if [ -n "$selected" ]; then
    echo "Opening $selected"
    $selected
else
    echo "No command selected"
fi